"""Added fields to book table

Revision ID: c2fed7ac7e35
Revises: 5ec150eac293
Create Date: 2023-08-25 11:04:07.524728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fed7ac7e35'
down_revision = '5ec150eac293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ratings_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('page_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('page_count')
        batch_op.drop_column('ratings_count')
        batch_op.drop_column('average_rating')

    # ### end Alembic commands ###
